12 delete comments
kalumwildig/BE---project pull request #12
Opened 2022-02-17 15:03 UTC by kalumwildig

2022-02-17 15:11 UTC, douglashellowell commented on controllers/controller.js
> +  getCommentModel
there's a syntax error here - you're missing a `,`!

i'm seeing a syntax error in your `app.test.js` too
Not sure if this is github being weird or if you missed it before commiting...?

2022-02-17 15:16 UTC, rogersop requested changes
See both mine and @douglashellowell's comments - we both started looking at the same time! 😅

2022-02-17 15:16 UTC, rogersop commented on controllers/controller.js
> +    await Promise.all([getCommentModel(id),deleteCommentModel(id)])
Slight overkill using your getCommentModel here, as the result object from the deleteCommentModel will let you know how many rows you have deleted with your query, which can be used to let the client know that either:
- the comment was successfully deleted, or
- the comment was not found

2022-02-17 15:19 UTC, douglashellowell requested changes
see both Paul and my own comments

have a check you haven't got some syntax errors in your code

Also, if you haven't got prettier installed please do!

2022-02-18 10:44 UTC, Augs0 approved these changes

2022-02-18 10:44 UTC, Augs0 commented on controllers/controller.js
> +   try { const id = req.params.comment_id
Just an organisational note, try to make sure your code is on new lines for readability :)

2022-02-18 10:45 UTC, merged